# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "86784ae493d9d7917a3448a59b105aa3"
name = "efficient-shipping-app"
handle = "efficient-shipping-app-9"
application_url = "https://contacted-evaluate-romania-nick.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "lapi-bazaar.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://contacted-evaluate-romania-nick.trycloudflare.com/auth/callback",
  "https://contacted-evaluate-romania-nick.trycloudflare.com/auth/shopify/callback",
  "https://contacted-evaluate-romania-nick.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
